<x-app-layout>
<x-slot name="header"><div class="flex items-center justify-between"><div><h2 class="text-xl font-semibold text-gray-800">Leads</h2><p class="text-sm text-gray-500">Pesquisa e filtros comerciais</p></div><div class="flex gap-2"><a href="{{ route('leads.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">Novo lead</a><a href="{{ route('crm.kanban') }}" class="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm text-slate-700">Kanban</a></div></div></x-slot>
<div class="py-8"><div class="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8">
<form method="GET" class="grid gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200 md:grid-cols-6">
<input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Nome, e-mail ou telefone" class="rounded-lg border-gray-300 text-sm md:col-span-2">
<select name="status" class="rounded-lg border-gray-300 text-sm"><option value="">Todos os status</option>@foreach(['open'=>'Aberto','won'=>'Ganho','lost'=>'Perdido'] as $v=>$l)<option value="{{ $v }}" @selected(($filters['status']??'')===$v)>{{ $l }}</option>@endforeach</select>
<select name="priority" class="rounded-lg border-gray-300 text-sm"><option value="">Prioridade</option>@foreach(['low'=>'Baixa','normal'=>'Normal','high'=>'Alta','urgent'=>'Urgente'] as $v=>$l)<option value="{{ $v }}" @selected(($filters['priority']??'')===$v)>{{ $l }}</option>@endforeach</select>
<select name="source" class="rounded-lg border-gray-300 text-sm"><option value="">Origem</option>@foreach($sources as $source)<option value="{{ $source }}" @selected(($filters['source']??'')===$source)>{{ $source }}</option>@endforeach</select>
<div class="flex gap-2"><button class="flex-1 rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white">Filtrar</button><a href="{{ route('leads.index') }}" class="rounded-lg border px-3 py-2 text-sm">Limpar</a></div>
<label class="flex items-center gap-2 text-sm md:col-span-6"><input type="checkbox" name="favorite" value="1" @checked(($filters['favorite']??'')==='1')> Somente favoritos</label>
</form>
<div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-5 py-3 text-left">Lead</th><th class="px-5 py-3 text-left">Etapa</th><th class="px-5 py-3 text-left">Origem</th><th class="px-5 py-3 text-left">Responsável</th><th class="px-5 py-3 text-right">Valor</th></tr></thead><tbody class="divide-y">@forelse($leads as $lead)<tr class="hover:bg-gray-50"><td class="px-5 py-4"><a href="{{ route('leads.show',$lead) }}" class="font-medium text-indigo-700">{{ $lead->is_favorite ? '★ ' : '' }}{{ $lead->name }}</a><p class="text-xs text-gray-500">{{ $lead->email ?: $lead->phone }}</p></td><td class="px-5 py-4">{{ $lead->stage?->name ?? 'Sem etapa' }}</td><td class="px-5 py-4">{{ $lead->source ?: '—' }}</td><td class="px-5 py-4">{{ $lead->owner?->name ?? 'Não atribuído' }}</td><td class="px-5 py-4 text-right font-medium">R$ {{ number_format((float)$lead->value,2,',','.') }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-500">Nenhum lead encontrado.</td></tr>@endforelse</tbody></table></div></div>
{{ $leads->links() }}
</div></div>
</x-app-layout>
