@extends('layouts.smartbiz')
@section('title', 'CRM — Lead 360°')
@push('styles') @include('crm.partials.theme') @endpush
@section('content')
@php
$statusMap=['open'=>'Aberto','won'=>'Ganho','lost'=>'Perdido'];
$healthMap=['healthy'=>['Saudável','text-emerald-300 bg-emerald-500/10'],'attention'=>['Atenção','text-amber-300 bg-amber-500/10'],'risk'=>['Em risco','text-rose-300 bg-rose-500/10']];
$health=$healthMap[$lead->health_status] ?? $healthMap['attention'];
@endphp
<div class="crm-shell crm-page"><div class="crm-container space-y-4">
<div class="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div class="flex items-center gap-4"><div class="grid h-14 w-14 place-items-center rounded-2xl bg-violet-500/15 text-xl font-black text-violet-300">{{ mb_strtoupper(mb_substr($lead->name,0,1)) }}</div><div><div class="crm-muted text-xs font-bold uppercase tracking-[.16em]">Lead 360°</div><h1 class="crm-title mt-1">{{ $lead->name }}</h1><p class="crm-subtitle">{{ $lead->stage?->name ?? 'Sem etapa' }} · {{ $lead->owner?->name ?? 'Não atribuído' }}</p></div></div><div class="flex flex-wrap gap-2"><a href="{{ route('crm.leads.edit',$lead) }}" class="crm-btn">Editar</a>@if($lead->phone)<a href="https://wa.me/55{{ preg_replace('/\D+/','',$lead->phone) }}" target="_blank" class="crm-btn crm-btn-primary">WhatsApp</a>@endif</div></div>
@include('crm.partials.nav')
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
@foreach([['Valor','R$ '.number_format((float)$lead->value,2,',','.')],['Score comercial',($lead->score??0).'/100'],['Health Score',($lead->health_score??50).'/100'],['Status',$statusMap[$lead->status]??ucfirst($lead->status)],['Follow-up',$lead->next_follow_up_at?->timezone('America/Sao_Paulo')->format('d/m/Y H:i')??'Não agendado']] as $m)<div class="crm-card crm-metric"><div class="crm-metric-label">{{ $m[0] }}</div><div class="mt-3 text-lg font-black">{{ $m[1] }}</div></div>@endforeach
</div>
<div class="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
<div class="space-y-4">
<div class="crm-card"><div class="crm-section-head"><div><h2 class="crm-section-title">Registrar atividade</h2><p class="crm-section-subtitle">Ligação, reunião, tarefa ou observação.</p></div></div><form method="POST" action="{{ route('crm.activities.store',$lead) }}" class="crm-body grid gap-3 md:grid-cols-2">@csrf<div><label class="crm-label">Tipo</label><select name="type" class="crm-select" required>@foreach(['note'=>'Observação','call'=>'Ligação','whatsapp'=>'WhatsApp','email'=>'E-mail','meeting'=>'Reunião','task'=>'Tarefa'] as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select></div><div><label class="crm-label">Prazo</label><input type="datetime-local" name="due_at" class="crm-input"></div><div class="md:col-span-2"><label class="crm-label">Título</label><input name="title" class="crm-input" required></div><div class="md:col-span-2"><label class="crm-label">Descrição</label><textarea name="description" class="crm-textarea"></textarea></div><div class="md:col-span-2 flex justify-end"><button class="crm-btn crm-btn-primary">Registrar atividade</button></div></form></div>
<div class="crm-card overflow-hidden"><div class="crm-section-head"><div><h2 class="crm-section-title">Timeline automática</h2><p class="crm-section-subtitle">Histórico auditável do relacionamento.</p></div><span class="crm-badge">{{ $lead->timelineEvents->count() }}</span></div><div class="crm-body space-y-3">@forelse($lead->timelineEvents as $event)<div class="rounded-xl border border-[var(--crm-border)] bg-[var(--crm-card-2)] p-4"><div class="flex items-start justify-between gap-3"><div><div class="text-sm font-bold">{{ $event->title }}</div><div class="crm-muted mt-1 text-xs">{{ $event->description }}</div></div><span class="crm-badge">{{ str_replace('_',' ',ucfirst($event->type)) }}</span></div><div class="crm-muted mt-3 text-[11px]">{{ $event->user?->name ?? 'Sistema' }} · {{ $event->created_at?->timezone('America/Sao_Paulo')->format('d/m/Y H:i') }}</div></div>@empty<div class="crm-empty">Os próximos eventos serão registrados automaticamente.</div>@endforelse</div></div>
<div class="crm-card"><div class="crm-section-head"><div><h2 class="crm-section-title">Comentários internos</h2></div></div><form method="POST" action="{{ route('crm.comments.store',$lead) }}" class="crm-body">@csrf<textarea name="body" class="crm-textarea" required placeholder="Escreva uma observação para a equipe..."></textarea><div class="mt-3 flex justify-end"><button class="crm-btn crm-btn-primary">Adicionar comentário</button></div></form><div class="crm-body space-y-3 border-t border-[var(--crm-border)]">@forelse($lead->comments as $comment)<div class="rounded-xl bg-[var(--crm-card-2)] p-4"><div class="text-sm">{{ $comment->body }}</div><div class="crm-muted mt-2 text-[11px]">{{ $comment->user?->name ?? 'Sistema' }} · {{ $comment->created_at?->timezone('America/Sao_Paulo')->format('d/m/Y H:i') }}</div></div>@empty<div class="crm-empty">Nenhum comentário interno.</div>@endforelse</div></div>
</div>
<aside class="space-y-4">
<div class="crm-card"><div class="crm-section-head"><div><h2 class="crm-section-title">Saúde do lead</h2></div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $health[1] }}">{{ $health[0] }}</span></div><div class="crm-body"><div class="flex items-end justify-between"><strong class="text-3xl">{{ $lead->health_score ?? 50 }}</strong><span class="crm-muted text-xs">de 100</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-violet-500" style="width: {{ $lead->health_score ?? 50 }}%"></div></div><p class="crm-muted mt-3 text-xs">Calculado por contato, responsável, atividade recente e follow-up.</p></div></div>
<div class="crm-card"><div class="crm-section-head"><div><h2 class="crm-section-title">Dados do lead</h2></div></div><div class="crm-body space-y-4">@foreach([['E-mail',$lead->email],['Telefone',$lead->phone],['Origem',$lead->source],['Campanha',$lead->campaign],['Pipeline',$lead->pipeline?->name],['Responsável',$lead->owner?->name]] as $i)<div><div class="crm-muted text-[11px] font-bold uppercase tracking-wider">{{ $i[0] }}</div><div class="mt-1 text-sm font-semibold">{{ $i[1] ?: 'Não informado' }}</div></div>@endforeach</div></div>
<div class="crm-card"><div class="crm-section-head"><div><h2 class="crm-section-title">Arquivos</h2></div><span class="crm-badge">{{ $lead->files->count() }}</span></div><form method="POST" enctype="multipart/form-data" action="{{ route('crm.files.store',$lead) }}" class="crm-body">@csrf<input type="file" name="file" class="crm-input" required><button class="crm-btn mt-3 w-full">Enviar arquivo</button></form><div class="crm-body space-y-2 border-t border-[var(--crm-border)]">@forelse($lead->files as $file)<div class="flex items-center justify-between gap-2 rounded-xl bg-[var(--crm-card-2)] p-3"><div class="min-w-0"><div class="truncate text-xs font-bold">{{ $file->original_name }}</div><div class="crm-muted text-[10px]">{{ number_format($file->size/1024,1,',','.') }} KB</div></div><div class="flex gap-1"><a class="crm-btn !px-2 !py-1 text-xs" href="{{ route('crm.files.download',$file) }}">Baixar</a><form method="POST" action="{{ route('crm.files.destroy',$file) }}">@csrf @method('DELETE')<button class="crm-btn !px-2 !py-1 text-xs">Excluir</button></form></div></div>@empty<div class="crm-empty">Nenhum arquivo.</div>@endforelse</div></div>
<div class="crm-card"><div class="crm-section-head"><div><h2 class="crm-section-title">Tags</h2></div></div><form method="POST" action="{{ route('crm.tags.sync',$lead) }}" class="crm-body">@csrf @method('PUT')<div class="space-y-2">@foreach($availableTags as $tag)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked($lead->tags->contains($tag->id))><span>{{ $tag->name }}</span></label>@endforeach</div><button class="crm-btn mt-4 w-full">Salvar tags</button></form></div>
</aside></div></div></div>
@endsection
