<x-app-layout>
<x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold text-gray-800">{{ $lead->name }}</h2><p class="text-sm text-gray-500">Visão 360º do relacionamento</p></div><div class="flex gap-2"><form method="POST" action="{{ route('leads.favorite',$lead) }}">@csrf @method('PATCH')<button class="rounded-lg border px-4 py-2 text-sm">{{ $lead->is_favorite ? '★ Favorito' : '☆ Favoritar' }}</button></form><a href="{{ route('leads.index') }}" class="rounded-lg border px-4 py-2 text-sm">Voltar</a></div></div></x-slot>
<div class="py-8"><div class="mx-auto grid max-w-7xl gap-6 px-4 sm:px-6 lg:grid-cols-3 lg:px-8">
<div class="space-y-6 lg:col-span-2">
<div class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><div class="grid gap-5 sm:grid-cols-2"><div><p class="text-xs uppercase text-gray-400">E-mail</p><p class="mt-1">{{ $lead->email ?: 'Não informado' }}</p></div><div><p class="text-xs uppercase text-gray-400">Telefone</p><p class="mt-1">{{ $lead->phone ?: 'Não informado' }}</p></div><div><p class="text-xs uppercase text-gray-400">Etapa</p><p class="mt-1">{{ $lead->stage?->name ?? 'Sem etapa' }}</p></div><div><p class="text-xs uppercase text-gray-400">Próximo follow-up</p><p class="mt-1">{{ $lead->next_follow_up_at?->format('d/m/Y H:i') ?? 'Não definido' }}</p></div></div></div>
<div class="rounded-xl bg-white p-5 shadow-sm ring-1 ring-gray-200"><h3 class="font-semibold">Tags</h3><form method="POST" action="{{ route('crm.leads.tags',$lead) }}" class="mt-4 flex flex-wrap gap-3">@csrf @method('PUT') @forelse($availableTags as $tag)<label class="flex items-center gap-2 rounded-full border px-3 py-2 text-sm"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked($lead->tags->contains($tag->id))><span class="h-2.5 w-2.5 rounded-full" style="background:{{ $tag->color }}"></span>{{ $tag->name }}</label>@empty<p class="text-sm text-gray-500">Cadastre tags pela base de dados ou API administrativa.</p>@endforelse @if($availableTags->isNotEmpty())<button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">Salvar tags</button>@endif</form></div>
<div class="rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><div class="border-b p-5"><h3 class="font-semibold">Nova atividade</h3></div><form method="POST" action="{{ route('crm.activities.store',$lead) }}" class="grid gap-4 p-5 sm:grid-cols-2">@csrf <select name="type" class="rounded-lg border-gray-300 text-sm" required><option value="note">Observação</option><option value="call">Ligação</option><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option><option value="meeting">Reunião</option><option value="task">Tarefa</option></select><input name="title" placeholder="Título" class="rounded-lg border-gray-300 text-sm" required><textarea name="description" rows="3" placeholder="Descrição" class="rounded-lg border-gray-300 text-sm sm:col-span-2"></textarea><input type="datetime-local" name="due_at" class="rounded-lg border-gray-300 text-sm"><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">Registrar</button></form></div>
<div class="rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><div class="border-b p-5"><h3 class="font-semibold">Timeline de atividades</h3></div><div class="divide-y">@forelse($lead->activities as $activity)<div class="p-5"><div class="flex justify-between gap-4"><div><p class="font-medium">{{ $activity->title }}</p><p class="mt-1 text-sm text-gray-600">{{ $activity->description }}</p><p class="mt-2 text-xs text-gray-400">{{ ucfirst($activity->type) }} · {{ $activity->user?->name ?? 'Sistema' }} · {{ $activity->created_at?->format('d/m/Y H:i') }}</p></div>@if(!$activity->completed_at)<form method="POST" action="{{ route('crm.activities.complete',$activity) }}">@csrf @method('PATCH')<button class="text-xs font-medium text-indigo-600">Concluir</button></form>@else<span class="text-xs text-emerald-600">Concluída</span>@endif</div></div>@empty<p class="p-6 text-sm text-gray-500">Nenhuma atividade.</p>@endforelse</div></div>
</div>
<div class="space-y-6"><div class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><h3 class="font-semibold">Resumo</h3><div class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><span class="text-gray-500">Status</span><strong>{{ ucfirst($lead->status) }}</strong></div><div class="flex justify-between"><span class="text-gray-500">Score</span><strong>{{ $lead->score }}/100</strong></div><div class="flex justify-between"><span class="text-gray-500">Prioridade</span><strong>{{ ucfirst($lead->priority ?? 'normal') }}</strong></div><div class="flex justify-between"><span class="text-gray-500">Valor</span><strong class="text-emerald-600">R$ {{ number_format((float)$lead->value,2,',','.') }}</strong></div></div></div>
<div class="rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><div class="border-b p-5"><h3 class="font-semibold">Comentários internos</h3></div><form method="POST" action="{{ route('crm.comments.store',$lead) }}" class="p-5">@csrf<textarea name="body" rows="3" required placeholder="Escreva uma observação para a equipe" class="w-full rounded-lg border-gray-300 text-sm"></textarea><button class="mt-3 rounded-lg bg-gray-900 px-4 py-2 text-sm text-white">Comentar</button></form><div class="divide-y">@forelse($lead->comments as $comment)<div class="p-5"><p class="text-sm text-gray-700">{{ $comment->body }}</p><p class="mt-2 text-xs text-gray-400">{{ $comment->user?->name ?? 'Sistema' }} · {{ $comment->created_at?->format('d/m/Y H:i') }}</p></div>@empty<p class="p-5 text-sm text-gray-500">Nenhum comentário.</p>@endforelse</div></div></div>
</div></div>
</x-app-layout>
