@once
    @push('styles')
        <style>
            .team-shell{--sb-bg:#0f0b17;--sb-card:#171320;--sb-card-2:#21192e;--sb-primary:#7c3aed;--sb-primary-2:#a855f7;--sb-text:#fff;--sb-muted:#a9a3b5;--sb-border:rgba(255,255,255,.08);--sb-success:#22c55e;--sb-danger:#ef4444;--sb-warning:#f59e0b;color:var(--sb-text);font-size:14px}
            .team-page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;margin-bottom:16px}.team-page-head h1{font-size:1.45rem;line-height:1.2;margin:0 0 4px;font-weight:800}.team-page-head p{margin:0;color:var(--sb-muted);font-size:.88rem}
            .team-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:38px;border-radius:10px;padding:8px 13px;font-size:.84rem;font-weight:750;text-decoration:none;border:1px solid transparent;transition:.2s ease}.team-btn-primary{color:#fff;background:linear-gradient(135deg,var(--sb-primary),var(--sb-primary-2));box-shadow:0 8px 20px rgba(124,58,237,.22)}.team-btn-primary:hover{transform:translateY(-1px);color:#fff}.team-btn-ghost{color:#e9e5ef;background:rgba(255,255,255,.035);border-color:var(--sb-border)}.team-btn-ghost:hover{color:#fff;background:rgba(255,255,255,.07)}
            .team-card{background:linear-gradient(180deg,rgba(255,255,255,.022),transparent),var(--sb-card);border:1px solid var(--sb-border);border-radius:15px;box-shadow:0 14px 34px rgba(0,0,0,.16)}
            .team-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-bottom:14px}.team-metric{padding:14px 15px;min-height:84px}.team-metric-label{color:var(--sb-muted);font-size:.76rem;margin-bottom:5px}.team-metric-value{font-size:1.42rem;line-height:1.1;font-weight:800}.team-metric-dot{width:8px;height:8px;border-radius:999px;display:inline-block;margin-right:6px}
            .team-toolbar{display:flex;gap:9px;padding:10px;margin-bottom:14px}.team-search{position:relative;flex:1}.team-search input,.team-field,.team-select{width:100%;min-height:40px;background:#120e1b!important;border:1px solid var(--sb-border)!important;color:#fff!important;border-radius:10px!important;padding:9px 12px!important;font-size:.85rem!important;box-shadow:none!important}.team-search input{padding-left:38px!important}.team-search span{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:var(--sb-muted)}.team-field::placeholder{color:#777182}.team-select option{background:#171320}
            .team-table-wrap{overflow:auto}.team-table{width:100%;border-collapse:separate;border-spacing:0}.team-table th{color:#918a9e;text-transform:uppercase;font-size:.65rem;letter-spacing:.075em;font-weight:750;padding:11px 13px;border-bottom:1px solid var(--sb-border);white-space:nowrap}.team-table td{padding:11px 13px;border-bottom:1px solid rgba(255,255,255,.055);vertical-align:middle;font-size:.82rem}.team-table tbody tr{transition:.18s ease}.team-table tbody tr:hover{background:rgba(124,58,237,.055)}.team-table tbody tr:last-child td{border-bottom:0}
            .team-user{display:flex;align-items:center;gap:10px;min-width:215px}.team-avatar{width:38px;height:38px;flex:0 0 38px;border-radius:11px;display:grid;place-items:center;font-size:.82rem;font-weight:800;color:#fff;background:linear-gradient(135deg,var(--sb-primary),#4f46e5);overflow:hidden;position:relative}.team-avatar img{display:block;width:100%;height:100%;object-fit:cover}.team-avatar-lg{width:82px;height:82px;flex-basis:82px;border-radius:21px;font-size:1.5rem}.team-avatar-dot{position:absolute;right:0;bottom:0;width:10px;height:10px;background:var(--sb-success);border:2px solid var(--sb-card);border-radius:50%}.team-name{font-size:.87rem;font-weight:800;color:#fff;line-height:1.25}.team-sub{font-size:.73rem;color:var(--sb-muted);margin-top:2px;line-height:1.35}
            .team-badge{display:inline-flex;align-items:center;border-radius:999px;padding:4px 8px;font-size:.67rem;font-weight:800;border:1px solid transparent}.team-badge-role{color:#cdbbff;background:rgba(124,58,237,.14);border-color:rgba(124,58,237,.25)}.team-badge-success{color:#86efac;background:rgba(34,197,94,.11);border-color:rgba(34,197,94,.24)}.team-badge-danger{color:#fca5a5;background:rgba(239,68,68,.11);border-color:rgba(239,68,68,.24)}
            .team-actions{display:flex;gap:6px;flex-wrap:wrap}.team-icon-btn{display:inline-grid;place-items:center;min-width:34px;height:32px;padding:0 9px;border-radius:9px;border:1px solid var(--sb-border);background:rgba(255,255,255,.025);color:#ded8e8;text-decoration:none;font-size:.72rem;font-weight:750}.team-icon-btn:hover{background:rgba(255,255,255,.07);color:#fff}.team-icon-edit{color:#d8c8ff;border-color:rgba(124,58,237,.3);background:rgba(124,58,237,.09)}.team-icon-danger{color:#fca5a5;border-color:rgba(239,68,68,.25)}
            .team-form-card{padding:18px}.team-section-title{font-weight:800;font-size:.9rem;margin-bottom:13px;padding-bottom:10px;border-bottom:1px solid var(--sb-border)}.team-form-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:12px}.team-col-4{grid-column:span 4}.team-col-6{grid-column:span 6}.team-col-12{grid-column:span 12}.team-label{display:block;font-size:.75rem;font-weight:700;color:#c7c0ce;margin-bottom:5px}.team-help{font-size:.69rem;color:var(--sb-muted);margin-top:5px}.team-form-footer{display:flex;justify-content:flex-end;gap:8px;margin-top:17px;padding-top:14px;border-top:1px solid var(--sb-border)}
            .team-alert{border-radius:11px;padding:10px 13px;margin-bottom:13px;border:1px solid;font-size:.82rem}.team-alert-danger{background:rgba(239,68,68,.1);border-color:rgba(239,68,68,.25);color:#fecaca}.team-alert-success{background:rgba(34,197,94,.1);border-color:rgba(34,197,94,.25);color:#bbf7d0}
            .team-profile-grid{display:grid;grid-template-columns:280px 1fr;gap:14px}.team-profile-main{padding:20px;text-align:center}.team-profile-main .team-avatar{margin:0 auto 12px}.team-profile-name{font-size:1.12rem;font-weight:800}.team-profile-info{padding:18px}.team-info-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.team-info-item{padding:11px;border-radius:11px;background:rgba(255,255,255,.025);border:1px solid var(--sb-border)}.team-info-label{font-size:.65rem;color:var(--sb-muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:4px}.team-info-value{font-size:.8rem;font-weight:700;word-break:break-word}.team-empty{text-align:center;padding:36px 18px;color:var(--sb-muted)}.team-pagination{padding:13px;border-top:1px solid var(--sb-border)}
            .team-avatar-upload{display:flex;align-items:center;gap:12px}.team-avatar-preview{width:46px;height:46px;flex:0 0 46px;border-radius:12px;overflow:hidden;display:grid;place-items:center;background:linear-gradient(135deg,var(--sb-primary),#4f46e5);font-weight:800}.team-avatar-preview img{width:100%;height:100%;object-fit:cover}.team-file-wrap{flex:1}
            @media(max-width:992px){.team-metrics{grid-template-columns:repeat(2,1fr)}.team-profile-grid{grid-template-columns:1fr}.team-col-4{grid-column:span 6}}
            @media(max-width:640px){.team-page-head{flex-direction:column}.team-page-head .team-btn{width:100%}.team-toolbar{flex-direction:column}.team-form-grid{display:block}.team-form-grid>div{margin-bottom:12px}.team-info-grid{grid-template-columns:1fr}.team-metrics{grid-template-columns:1fr}.team-table th:nth-child(2),.team-table td:nth-child(2){display:none}}
        </style>
    @endpush
@endonce
