@csrf
<div class="row g-4">
    <div class="col-md-6"><label class="form-label">Nome *</label><input type="text" name="name" value="{{ old('name', $lead->name ?? '') }}" class="form-control" required></div>
    <div class="col-md-3"><label class="form-label">Telefone</label><input type="text" name="phone" value="{{ old('phone', $lead->phone ?? '') }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">E-mail</label><input type="email" name="email" value="{{ old('email', $lead->email ?? '') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Empresa</label><select name="company_id" class="form-select"><option value="">Sem empresa</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected(old('company_id', $lead->company_id ?? '') == $company->id)>{{ $company->trade_name ?: $company->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Pipeline</label><select name="pipeline_id" class="form-select"><option value="">Selecione</option>@foreach($pipelines as $pipeline)<option value="{{ $pipeline->id }}" @selected(old('pipeline_id', $lead->pipeline_id ?? '') == $pipeline->id)>{{ $pipeline->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Etapa</label><select name="stage_id" class="form-select"><option value="">Selecione</option>@foreach($stages as $stage)<option value="{{ $stage->id }}" @selected(old('stage_id', $lead->stage_id ?? '') == $stage->id)>{{ $stage->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Responsável</label><select name="assigned_user_id" class="form-select"><option value="">Sem responsável</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('assigned_user_id', $lead->assigned_user_id ?? '') == $user->id)>{{ $user->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Origem</label><input type="text" name="source" value="{{ old('source', $lead->source ?? 'Manual') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Campanha</label><input type="text" name="campaign" value="{{ old('campaign', $lead->campaign ?? '') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Valor estimado</label><input type="number" step="0.01" name="value" value="{{ old('value', $lead->value ?? 0) }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select"><option @selected(old('status', $lead->status ?? 'Novo')=='Novo')>Novo</option><option @selected(old('status', $lead->status ?? '')=='Em atendimento')>Em atendimento</option><option @selected(old('status', $lead->status ?? '')=='Convertido')>Convertido</option><option @selected(old('status', $lead->status ?? '')=='Perdido')>Perdido</option></select></div>
    <div class="col-md-4"><label class="form-label">Prioridade</label><select name="priority" class="form-select"><option @selected(old('priority', $lead->priority ?? 'Normal')=='Baixa')>Baixa</option><option @selected(old('priority', $lead->priority ?? 'Normal')=='Normal')>Normal</option><option @selected(old('priority', $lead->priority ?? '')=='Alta')>Alta</option></select></div>
    <div class="col-md-12"><label class="form-label">Observações</label><textarea name="notes" class="form-control" rows="4">{{ old('notes', $lead->notes ?? '') }}</textarea></div>
</div>
<div class="mt-4 text-end"><button class="btn btn-primary px-5" type="submit" onsubmit="this.disabled=true">Salvar Lead</button></div>
