<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?> <?php $__env->slot('header', null, []); ?> <div class="flex justify-between"><div><h2 class="text-xl font-semibold">Kanban CRM</h2><p class="text-sm text-gray-500">Pipeline comercial</p></div><a href="<?php echo e(route('crm.dashboard')); ?>" class="rounded-lg border px-4 py-2 text-sm">Dashboard</a></div> <?php $__env->endSlot(); ?><div class="py-8"><div class="mx-auto max-w-full px-4 sm:px-6 lg:px-8"><?php $__empty_1 = true; $__currentLoopData = $pipelines; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pipeline): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><h3 class="mb-4 text-lg font-semibold"><?php echo e($pipeline->name); ?></h3><div class="mb-8 flex gap-4 overflow-x-auto pb-4"><?php $__currentLoopData = $pipeline->stages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $stage): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><section class="w-80 flex-none rounded-xl bg-gray-100 p-3"><div class="mb-3 flex justify-between"><div><h4 class="font-semibold"><?php echo e($stage->name); ?></h4><p class="text-xs text-gray-500"><?php echo e($stage->leads->count()); ?> leads</p></div><span class="rounded-full bg-white px-2 py-1 text-xs"><?php echo e($stage->probability); ?>%</span></div><div class="space-y-3"><?php $__empty_2 = true; $__currentLoopData = $stage->leads; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $lead): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><a href="<?php echo e(route('leads.show',$lead)); ?>" class="block rounded-lg bg-white p-4 shadow-sm"><p class="font-medium"><?php echo e($lead->name); ?></p><p class="text-sm text-gray-500"><?php echo e($lead->owner?->name ?? 'Não atribuído'); ?></p><p class="mt-3 font-semibold text-emerald-600">R$ <?php echo e(number_format((float)$lead->value,2,',','.')); ?></p></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><div class="rounded-lg border border-dashed p-5 text-center text-sm text-gray-400">Nenhum lead</div><?php endif; ?></div></section><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="rounded-xl bg-white p-8 text-center">Nenhum pipeline configurado.</div><?php endif; ?></div></div> <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\laragon\www\smartbiz-enterprise\resources\views/crm/kanban.blade.php ENDPATH**/ ?>